module.exports = {
  TOKEN: 'xoxb-249271027507-Wpoe9LWDjTmvrg7LyaRpBnpV',
  CHANNELS: {
    SHARING: 'CCB1ENNP7'
  },
  MAX_SCORE_SHARING_WEEK: 10,
  SCORE_SHARING: 2,
  MAX_SCORE_INTERACTIVE_WEEK: 10,
  SCORE_INTERACTIVE: 1
}

